blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/ethanphan3993/Model-Advisor/discussions
    about: Open a Discussion for usage questions, design ideas, or anything not bug/feature.
